### ISSUE TITLE
New results for Firefox 123.0 (no partition)

### ISSUE THREAD

**Issue by mcdamo** [eight04/webext-hit-the-cache#1]
Thankyou for this tool!

Behavior has changed in Firefox 123.0 with _no partition_, the background fetch can no longer use cache:

| Case                      | Hit the server | Success | File size |
| ------------------------- | -------------- | ------- | --------- |
| backgroundFetch           | 2              | true    | /564      |
| backgroundFetchNoCors     | 2              | true    | /564      |
| backgroundXHR             | 2              | true    | /564      |
| backgroundDownload        | 1              | true    | /564      |
| backgroundDownloadWithRef | 1              | true    | /564      |
| contentFetch              | 1              | true    | /564      |
| contentFetchNoCors        | 1              | true    | /564      |
| contentXHR                | 1              | true    | /564      |
| pageFetch                 | 2              | false   |           |
| pageFetchNoCors           | 2              | true    | /0        |
| pageXHR                   | 2              | false   |           |

**Comment by eight04** [comment]
I can reproduce on Windows 10 + Nightly 125.0a1

| Case                      | Hit the server | Success | File size |
| ------------------------- | -------------- | ------- | --------- |
| backgroundFetch           | 2              | true    | /564      |
| backgroundFetchNoCors     | 2              | true    | /564      |
| backgroundXHR             | 2              | true    | /564      |
| backgroundDownload        | 1              | true    | /564      |
| backgroundDownloadWithRef | 1              | true    | /564      |
| contentFetch              | 1              | true    | /564      |
| contentFetchNoCors        | 1              | true    | /564      |
| contentXHR                | 1              | true    | /564      |
| pageFetch                 | 2              | false   |           |
| pageFetchNoCors           | 2              | true    | /0        |
| pageXHR                   | 2              | false   |           |

**Comment by eight04** [comment]
README updated!
